# Generated by Django 3.1.7 on 2021-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='course_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
