# Generated by Django 3.2 on 2021-05-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=30, null=True)),
                ('lab_id', models.IntegerField(null=True)),
                ('TA', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LabSection',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.course'),
        ),
    ]
