# Generated by Django 3.1.7 on 2021-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0002_auto_20210518_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
