# Generated by Django 3.2 on 2021-04-28 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TA_Scheduler', '0003_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('course_section_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Section ID')),
                ('course_section_code', models.CharField(max_length=3, verbose_name='Course Section Code')),
                ('lecture_days', models.CharField(blank=True, max_length=6, verbose_name='Lecture Day(s)')),
                ('lecture_time', models.TextField(blank=True, max_length=12, verbose_name='Lecture Time')),
                ('course_id', models.ForeignKey(help_text='Course ID', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.course')),
                ('instructor_id', models.ForeignKey(blank=True, help_text='Instructor ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ta_ids', models.ManyToManyField(blank=True, help_text="Ta's Assigned to this Course Section", related_name='section_assign', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_section_code', 'course_id')},
            },
        ),
        migrations.DeleteModel(
            name='Course2',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='home_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
