# Generated by Django 3.2 on 2021-04-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0004_auto_20210428_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
