# Generated by Django 3.2 on 2021-04-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0005_remove_account_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
