# Generated by Django 3.2 on 2021-05-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TA_Scheduler', '0006_delete_coursesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='cId',
        ),
        migrations.AddField(
            model_name='course',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='DEFAULT_VALUE', max_length=10),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('course_section_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Section ID')),
                ('course_section_code', models.CharField(max_length=3, verbose_name='Course Section Code')),
                ('lecture_days', models.CharField(blank=True, max_length=6, verbose_name='Lecture Day(s)')),
                ('lecture_time', models.TextField(blank=True, max_length=12, verbose_name='Lecture Time')),
                ('course_id', models.ForeignKey(help_text='Course ID', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.course')),
                ('instructor_id', models.ForeignKey(blank=True, help_text='Instructor ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ta_ids', models.ManyToManyField(blank=True, help_text="Ta's Assigned to this Course Section", related_name='section_assign', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_section_code', 'course_id')},
            },
        ),
    ]
