# Generated by Django 3.2 on 2021-04-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0006_delete_coursesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='number',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
