# Generated by Django 3.2 on 2021-05-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0007_auto_20210502_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='User ID (Autogenerated)')),
                ('type', models.CharField(choices=[('A', 'Administrator'), ('P', 'Professor'), ('T', 'TA')], max_length=1, verbose_name='User Type')),
                ('univ_id', models.CharField(max_length=20, verbose_name='University ID')),
                ('l_name', models.CharField(blank=True, max_length=20, verbose_name='Last Name')),
                ('f_name', models.CharField(blank=True, max_length=20, verbose_name='First Name')),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(max_length=64)),
                ('tmp_password', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduler.user'),
        ),
    ]
