# Generated by Django 3.2 on 2021-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0008_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
