# Generated by Django 3.2 on 2021-04-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0008_remove_course_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
