# Generated by Django 3.2 on 2021-05-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0009_rename_course_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
