# Generated by Django 3.2 on 2021-05-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0009_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admin_id',
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
