# Generated by Django 3.2 on 2021-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0010_auto_20210508_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
