# Generated by Django 3.2 on 2021-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0014_auto_20210509_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
