# Generated by Django 3.2 on 2021-05-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0015_auto_20210509_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('office_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('instructorOrTa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.account')),
            ],
        ),
    ]
