# Generated by Django 3.2 on 2021-05-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0016_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructorOrTa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.account'),
        ),
    ]
