# Generated by Django 3.2 on 2021-05-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0017_course_instructororta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('meeting_time', models.CharField(max_length=20)),
                ('meeting_location', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.course')),
                ('instructorOrTa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
